spring.application.name=UserService
server.port=8080

# ===============================
# Database Configuration
# ===============================
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/vertx_db
db.username=postgres
db.password=password

# ===============================
# JPA / Hibernate
# ===============================
hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update

# ===============================
# Connection Pool
# ===============================
db.pool.initialSize=5
db.pool.maxTotal=20
